export default {
        books: [
                {
                        category: "books",
                        featuredCategory: "Comics & Graphic Novels",
                        id: 1,
                        name: "It Ends with Us: A Novel (Volume 1)",
                        image: "https://images-na.ssl-images-amazon.com/images/I/71EwoNQypZL._AC._SR360,460.jpg",
                        author: "Colleen Hoover", 
                        price: 15.09,
                        stars: 4.5, 
                        reviews: 72291,
                },
                {
                        category: "books",
                        featuredCategory: "Professional & Technical",
                        id: 2,
                        name: "Atomic Habits: An Easy & Proven Way to Build Good Habits & Break Bad Ones",
                        image: "https://images-na.ssl-images-amazon.com/images/I/81wgcld4wxL._AC._SR360,460.jpg",
                        author: "James Clear",
                        price: 21.66,
                        stars: 4.5, 
                        reviews: 71143,
                },
                {
                        category: "books",
                        id: 4,
                        featuredCategory: "Comics & Graphic Novels",
                        name: "Reminders of Him: A Novel",
                        image: "https://images-na.ssl-images-amazon.com/images/I/617uZq23IPL._AC._SR360,460.jpg",
                        author: "Colleen Hoover",
                        price: 12.28,
                        stars: 4.0, 
                        reviews: 76078,
                },
                {
                        category: "books",
                        featuredCategory: "Comics & Graphic Novels",
                        id: 5,
                        name: "Verity",
                        image: "https://images-na.ssl-images-amazon.com/images/I/610QYM5NxRL._AC._SR360,460.jpg",
                        author: "Colleen Hoover",
                        price: 15.50,
                        stars: 4.0, 
                        reviews: 57591,
                },
                {
                        category: "books",
                        featuredCategory: "Professional & Technical",
                        id: 6,
                        name: "The Fiber Fueled Cookbook: Inspiring Plant-Based Recipes to Turbocharge Your Health",
                        image: "https://images-na.ssl-images-amazon.com/images/I/91cDoM87dYL._AC._SR360,460.jpg",
                        author: "Will Bulsiewicz MD",
                        price: 26.5,
                        stars: 4.5, 
                        reviews: 119,
                },
                {
                        category: "books",
                        id: 7,
                        featuredCategory: "Comics & Graphic Novels",
                        name: "The Seven Husbands of Evelyn Hugo: A Novel",
                        image: "https://images-na.ssl-images-amazon.com/images/I/71pQQ9mk8eL._AC._SR360,460.jpg",
                        author: "Taylor Jenkins Reid",
                        price: 14.70,
                        stars: 4.0, 
                        reviews: 64109,
                },
                {
                        category: "books",
                        featuredCategory: "Comics & Graphic Novels",
                        id: 8,
                        name: "Where the Crawdads Sing",
                        image: "https://images-na.ssl-images-amazon.com/images/I/61m1Vxw8tiL._AC._SR360,460.jpg",
                        author: "Delia Owens",
                        price: 15.50,
                        stars: 4.0, 
                        reviews: 219108,
                },
                {
                        category: "books",
                        featuredCategory: "Comics & Graphic Novels",
                        id: 9,
                        name: "The Boy, the Mole, the Fox and the Horse",
                        image: "https://images-na.ssl-images-amazon.com/images/I/71eJk7GtUOL._AC._SR360,460.jpg",
                        author: "Charlie Mackesy",
                        price: 16.98,
                        stars: 5.0, 
                        reviews: 102263,
                },
                {
                        category: "books",
                        featuredCategory: "Science & Math",
                        id: 10,
                        name: "The Body Keeps the Score: Brain, Mind, and Body in the Healing of Trauma",
                        image: "https://images-na.ssl-images-amazon.com/images/I/61NdJMwAThS._AC._SR360,460.jpg",
                        author: "Bessel van der Kolk M.D.",
                        price: 15.07,
                        stars: 4.5, 
                        reviews: 49340,
                },
                {
                        category: "books",
                        featuredCategory: "Textbooks",
                        id: 11,
                        name: "The Wars of the Roses",
                        image: "https://images-na.ssl-images-amazon.com/images/I/7185cinqDOL._AC._SR360,460.jpg",
                        author: "Michael Hicks",
                        price: 32.50,
                        stars: 4.5, 
                        reviews: 54,
                },
                {
                        category: "books",
                        featuredCategory: "Children's Books",
                        id: 12,
                        name: "First 100 Words: A Padded Board Book",
                        image: "https://images-na.ssl-images-amazon.com/images/I/71aMpgf078L._AC._SR360,460.jpg",
                        author: "Roger Priddy",
                        price: 5.99,
                        stars: 4.5, 
                        reviews: 32293,
                },
                {
                        category: "books",
                        featuredCategory: "Eduaction & Reference",
                        id: 13,
                        name: "Atlas of the Heart: Mapping Meaningful Connection and the Language of Human Experience",
                        image: "https://images-na.ssl-images-amazon.com/images/I/91DNhLLmUOL._AC._SR360,460.jpg",
                        author: "Brené Brown",
                        price: 24.14,
                        stars: 4.5, 
                        reviews: 12142,
                },
                {
                        category: "books",
                        featuredCategory: "Politics & Socail Sciences",
                        id: 14,
                        name: "The Freedom Convoy: The Inside Story of Three Weeks that Shook the World",
                        image: "https://images-na.ssl-images-amazon.com/images/I/71EzllGpnBL._AC._SR360,460.jpg",
                        author: "Andrew Lawton",
                        price: 18.51,
                        stars: 4.0, 
                        reviews: 55,
                },
                {
                        category: "books",
                        featuredCategory: "Politics & Socail Sciences",
                        id: 15,
                        name: "Color & Frame - By the Sea (Adult Coloring Book)",
                        image: "https://images-na.ssl-images-amazon.com/images/I/91jW9T0PatL._AC._SR360,460.jpg",
                        author: "New Seasons",
                        price: 3.19,
                        stars: 4.5, 
                        reviews: 4903,
                },
        ]
}
